# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

title: 100% Renewables & Transparent Leadership
url: https://maclimatedemocracy.org/

menu:
  - title: Home
    page: /
  - title: Learn more
    page: /info
  - title: Sign the pledge
    page: /#sign
  - title: Volunteer
    page: /vol

include: ["_pages"]
exclude:
  - README.md
  - .circleci
  - vendor
  - node_modules
donate_button_url: https://secure.actblue.com/donate/act-on-mass
